version: 2

sources:
  - name: staging
    database: data-axiom-412014
     # For postgres:
      #database: production
    schema: trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_trips
      - name: yellow_trips
         # freshness:
           # error_after: {count: 6, period: hour}
      - name: fhv_2019

